#!/bin/bash
#SBATCH -A uot189
#SBATCH --job-name="netflix.local"
#SBATCH --output="netflix.local.out"
#SBATCH --partition=shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --mem=16G
#SBATCH --export=ALL 
#SBATCH --time=10

module load cpu/0.15.4 gcc/7.5.0 openjdk hadoop/3.2.2 spark

rm -rf output small-output.txt
spark-submit --class Netflix --master local[2] netflix.jar small-ratings.txt small-titles.txt output
cat output/part* >small-output.txt
